# Generated by Django 4.0 on 2022-01-02 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=100)),
                ('post_entity', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.user')),
            ],
        ),
    ]
