# Generated by Django 4.0 on 2022-01-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_value',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
